branch-defaults:
  eb:
    environment: deep-dev
global:
  application_name: deep-prod
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker 1.12.6
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
