version: '2'

services:
    nginx:
        restart: always
        build: ./nginx/
        ports:
            - "80:80"
        volumes:
            - static:/var/www/static
            - media:/var/www/media
            - socket:/home/code/deep/socket
        volumes_from:
            - django
        links:
            - django:django
        command: bash -c "service nginx start"

    django:
        restart: always
        build:
            context: ./django
            args:
                BUILD: 0
        expose:
            - "80"
        volumes:
            - static:/var/www/static
            - media:/var/www/media
            - socket:/home/code/deep/socket
            - /home/code/deep/hurricanematthewsos
            - /home/code/deep/deploy
        env_file: .env
        command: bash -c "chmod +x /home/code/deep/deploy/django/exec.sh && /home/code/deep/deploy/django/exec.sh"

volumes:
    socket:
    static:
    media:
